### ISSUE TITLE
Cannot read property 'WebSocket' of undefined

### ISSUE THREAD

**Issue by maluramichael** [zalmoxisus/remote-redux-devtools#6] opened 2016-01-21 09:17 UTC
I get the error message on iOS right after i import devTools with `import devTools from 'remote-redux-devtools';` in my store.js.

![screen shot 2016-01-21 at 10 17 15](https://cloud.githubusercontent.com/assets/1489383/12476222/2e1bb568-c028-11e5-8cca-eae5023d87a1.png)

**Comment by zalmoxisus** [comment] 2016-01-21 09:28
Could you please try to use version `0.0.8` instead to see if it is related to the changes in [`ws`](https://github.com/websockets/ws)?

What version of iOS and React Native do you use? Is this happen on emulator, on real device or both?

**Comment by zalmoxisus** [comment] 2016-01-22 13:14
Hey @maluramichael,

Here's [the reason](https://github.com/webpack/webpack-dev-server/issues/174#issuecomment-102303060) and [the solution](https://github.com/webpack/webpack-dev-server/issues/174#issuecomment-102391902) for this problem. In other words, you shouldn't compile dependencies with babel.

Please let me know whether it helps.

**Comment by robclouth** [comment] 2016-03-23 01:32
Hey, I'm getting this now. I'm using React Native. Where would I put the exclude? I've never used webpack before.

Thanks

**Comment by alex3t** [comment] 2016-03-23 04:22
same issue(at least on iOS simulator) with latest version of react-native(0.22), downgrade to 0.0.8 did not help. all working before upgrade to react-native 0.22 from 0.21
react-native packager doesnt use webpack

**Comment by mlabrum** [comment] 2016-03-23 04:46
@alex3t I just wrote a quick package.json `postInstall` task to replace 

File: `node_modules/sc-ws/lib/browser.js`
`var WebSocket = global.WebSocket || global.MozWebSocket;`
with
`var WebSocket = this.WebSocket || global.MozWebSocket;`


that seemed to fix it for me

**Comment by zalmoxisus** [comment] 2016-03-23 08:58
@robclouth,
Instead of `{ test: /\.js$/, loader: 'babel' }` you should have `{ test: /\.js$/, loader: 'babel', exclude: /node_modules/ }`, if that is the case.

@mlabrum, could you please check as well if it is not babel spoiling the dependency (as indicated in https://github.com/webpack/webpack-dev-server/issues/174). As you see from the line above the replacement, `global` should be the same as `this`.

**Comment by tpisto** [comment] 2016-03-23 13:02
I can confirm at Android using v0.1.5, react-native v0.22 and the vanilla react-packager

**Comment by zalmoxisus** [comment] 2016-03-23 15:37
Could you please try `npm i socketcluster-client@4.3.10`? It should fix the issue, though not sure React Native uses `window` object. Thanks to @jondubois for the fix!

**Comment by alex3t** [comment] 2016-03-23 16:03
tried both `npm i socketcluster-client@4.3.10` and @mlabrum `node_modules/sc-ws/lib/browser.js` fix, its working but got another error after several secs: ` 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions` related to socketcluster-client 
![simulator screen shot 23 mar 2016 23 02 38](https://cloud.githubusercontent.com/assets/53978/13991617/774e7f50-f14b-11e5-9ce7-858139182cbf.png)

**Comment by zalmoxisus** [comment] 2016-03-23 16:13
@alex3t, thanks for the info.

So there're two solutions to make `socketcluster-client` to work in strict mode (which should be investigated [here](https://github.com/SocketCluster/socketcluster-client/issues/45)) or to disable strict mode manually in `.babelrc` as follows:
```js
{
  "presets": [
    "react-native"
  ],
  "plugins": [
    ["transform-es2015-modules-commonjs", { "strict": false, "allowTopLevelThis": true }]
  ]
}
```

**Comment by zalmoxisus** [comment] 2016-03-24 08:46
@alex3t @tpisto @mlabrum @robclouth should be fixed in `socketcluster-client@4.3.11`. Please give it a try, make sure to also `sc-errors` to be updated.

**Comment by alex3t** [comment] 2016-03-24 14:55
yes, it works with latest  socketcluster-client and sc-errors

**Comment by robclouth** [comment] 2016-04-03 10:30
Yup, it works. Thanks!

**Comment by zalmoxisus** [comment] 2016-04-03 10:31
Thanks for the feedback! Closing then.

**Closed by zalmoxisus** 2016-04-03 10:31 UTC
